### ISSUE TITLE
Concerns regarding interference with law enforcement

### ISSUE THREAD

**Issue by ghost** [kellibrooke/ICE-tracker#34]
If criminals gain knowledge of ICE operations, the effectiveness of ICE could be jeopardized.

Does this concern you?

**Comment by reneesarley** [comment]
No this doesn't concern me.

**Comment by ghost** [comment]
Why does it not concern you?

Does my concern land on your "pro" or "con" list?

Is this a feature or a bug?

**Comment by reneesarley** [comment]
The functionality of the app Redad Alertas was used as a guide for the functionality of ICE Breaker. Your concern doesn't land on any list, pro, con, feature, bug or otherwise since Redad Alertas was based on the concerns of the community that is adversely impacted by ICE.

**Comment by ghost** [comment]
Crininals are adversely impacted by ICE. If criminals gain knowledge of ICE operations from your app, those criminals can out maneuver and flee ICE (or worse).

As far as I can tell, the entire point of your app is to deter the effectiveness of ICE.

You are opposed to law enforcement. You support criminals.

**Comment by reneesarley** [comment]
Okay.

**Comment by ghost** [comment]
I will consider "Okay" to be an admission to my assertion.

Thank you for being honest.
